server:
  servlet:
    context-path: /me
  port: 8081

spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
